server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: ${GATEWAY_CONNECT_TIMEOUT:6000}
            response-timeout: ${GATEWAY_RESPONSE_TIMEOUT:10s}

      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userCb
                fallbackUri: forward:/fallback/user

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/email,/api/email/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationCb
                fallbackUri: forward:/fallback/notification
      discovery:
        locator:
          enabled: ${GATEWAY_DISCOVERY_LOCATOR_ENABLED:false}
          lower-case-service-id: ${GATEWAY_DISCOVERY_LOCATOR_LOWERCASE:true}

resilience4j:
  timelimiter:
    instances:
      notificationCb:
        timeout-duration: ${NOTIFICATION_CB_TIMEOUT=8s}
      userCb:
        timeout-duration: ${USER_CB_TIMEOUT:4s}


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,circuitbreakerevents
  endpoint:
    health:
      probes:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka}

