server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          httpclient:
            connect-timeout: 6000
            response-timeout: 10s

          routes:
            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCb
                    fallbackUri: forward:/fallback/user

            - id: notification-service
              uri: lb://notification-service
              predicates:
                - Path=/api/email,/api/email/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: notificationCb
                    fallbackUri: forward:/fallback/notification
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true

resilience4j:
  timelimiter:
    instances:
      notificationCb:
        timeout-duration: 8s
      userCb:
        timeout-duration: 4s


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway,circuitbreakerevents
  endpoint:
    health:
      probes:
        enabled: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

