server:
  port: 8082

spring:
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring.json.add.type.headers: false

        acks: all
        retries: 5

  application:
    name: user-service

management:
  endpoints:
    web:
      exposure:
        include: health, info


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka